[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/produtos"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 